name: Scraper Trigger 

on:
    repository_dispatch:
        types: [remote_trigger] 
    workflow_dispatch: 
jobs:
    run_scraper:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            
            - name: Install dependencies
              run: |
                pip install -r requirements.txt
            
            - name: Install Playwright Browsers
              run: python -m playwright install --with-deps chromium

            - name: Run application code
              env:
                # AWS Redshift Connection Details
                REDSHIFT_HOST: ${{ vars.REDSHIFT_HOST }}
                REDSHIFT_DATABASE: ${{ vars.REDSHIFT_DATABASE }}
                REDSHIFT_USER: ${{ vars.REDSHIFT_USER }}
                REDSHIFT_PASSWORD: ${{ secrets.REDSHIFT_PASSWORD }}
                REDSHIFT_PORT: ${{ vars.REDSHIFT_PORT }}
                
              run: python scraper_playwright.py
