import pytest

from unit_testing.individual_test.export_testing import test_export
from unit_testing.individual_test.network_testing import test_networking
from unit_testing.individual_test.scraper_testing import test_scraper
from unit_testing.individual_test.sheet_testing import test_sheet
from unit_testing.individual_test.telegram_testing import test_telegram


